image:
  repository: ""

nameOverride: ""

resources:
  limits:
    cpu: "0.5"
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 512Mi

db:
  host: ""
  user: ""
  # Name of a Kubernetes Secret containing a DB_PASSWORD key
  existingSecret: ""
